-- ============================================================
-- ICT371 PostgreSQL Scenario Assignment
-- Scenario 1: University Library Book Loans
-- Student: Stanslous Chipampe  |  Student Number: 202406233
-- ============================================================

-- ---- Task 1: Create tables and seed data ----
DROP TABLE IF EXISTS book_loans CASCADE;
DROP TABLE IF EXISTS books CASCADE;

CREATE TABLE books (
    book_id         integer PRIMARY KEY,
    title           text NOT NULL,
    available_copies integer NOT NULL CHECK (available_copies >= 0)
);

CREATE TABLE book_loans (
    loan_id         integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    book_id         integer NOT NULL REFERENCES books(book_id),
    student_number  text NOT NULL,
    quantity        integer NOT NULL CHECK (quantity > 0),
    status          text NOT NULL CHECK (status IN ('ACTIVE', 'RETURNED'))
);

INSERT INTO books (book_id, title, available_copies)
VALUES (1, 'Database Systems: The Complete Book', 4),
       (2, 'Introduction to Algorithms', 1),
       (3, 'Computer Networking: A Top-Down Approach', 6);

SELECT * FROM books ORDER BY book_id;
-- Expected: 3 rows (book 1: 4 copies, book 2: 1 copy, book 3: 6 copies)

-- ---- Task 2: IF ELSIF ELSE on copy availability ----
DO $$
DECLARE
    v_copies integer;
BEGIN
    SELECT available_copies INTO v_copies
    FROM books WHERE book_id = 2;

    IF v_copies = 0 THEN
        RAISE NOTICE 'Book unavailable';
    ELSIF v_copies <= 1 THEN
        RAISE NOTICE 'Book low on copies: % remaining', v_copies;
    ELSE
        RAISE NOTICE 'Book sufficiently stocked: % remaining', v_copies;
    END IF;
END;
$$ LANGUAGE plpgsql;
-- Expected message: "Book low on copies: 1 remaining"

-- ---- Task 3: WHILE loop (overdue reminders) and FOR loop (shelf numbers) ----
DO $$
DECLARE
    v_reminder integer := 1;
BEGIN
    WHILE v_reminder <= 3 LOOP
        RAISE NOTICE 'Overdue reminder #%', v_reminder;
        v_reminder := v_reminder + 1;
    END LOOP;

    FOR v_shelf IN 1..3 LOOP
        RAISE NOTICE 'Checking shelf number %', v_shelf;
    END LOOP;
END;
$$ LANGUAGE plpgsql;
-- Expected: 3 overdue reminder notices, then 3 shelf-number notices

-- ---- Task 4: borrow_book procedure ----
CREATE OR REPLACE PROCEDURE borrow_book(
    p_book_id        integer,
    p_student_number text,
    p_quantity       integer
)
LANGUAGE plpgsql
AS $$
DECLARE
    v_available integer;
    v_loan_id   integer;
BEGIN
    IF p_quantity <= 0 THEN
        RAISE EXCEPTION 'Quantity must be positive'
            USING ERRCODE = '22023';
    END IF;

    SELECT available_copies INTO v_available
    FROM books
    WHERE book_id = p_book_id
    FOR UPDATE;

    IF NOT FOUND THEN
        RAISE NOTICE 'Book % does not exist', p_book_id;
        RETURN;
    ELSIF v_available < p_quantity THEN
        RAISE NOTICE 'Insufficient copies: only % available', v_available;
        RETURN;
    END IF;

    UPDATE books
    SET available_copies = available_copies - p_quantity
    WHERE book_id = p_book_id;

    INSERT INTO book_loans (book_id, student_number, quantity, status)
    VALUES (p_book_id, p_student_number, p_quantity, 'ACTIVE')
    RETURNING loan_id INTO v_loan_id;

    RAISE NOTICE 'Loan % created for student %', v_loan_id, p_student_number;
END;
$$;

-- ---- Task 5: Call borrow_book — two valid, one exceeding stock ----
CALL borrow_book(1, 'STU101', 2);
CALL borrow_book(3, 'STU102', 1);
CALL borrow_book(2, 'STU103', 5);   -- exceeds the 1 copy available

SELECT * FROM books ORDER BY book_id;
-- Expected: book 1 -> 2 copies, book 2 -> 1 copy (unchanged), book 3 -> 5 copies

SELECT * FROM book_loans ORDER BY loan_id;
-- Expected: 2 ACTIVE loans only (loan for STU103 was never created)

-- ---- Task 6: return_book procedure (idempotent on repeat call) ----
CREATE OR REPLACE PROCEDURE return_book(p_loan_id integer)
LANGUAGE plpgsql
AS $$
DECLARE
    v_book_id  integer;
    v_quantity integer;
BEGIN
    SELECT book_id, quantity
    INTO v_book_id, v_quantity
    FROM book_loans
    WHERE loan_id = p_loan_id AND status = 'ACTIVE'
    FOR UPDATE;

    IF NOT FOUND THEN
        RAISE NOTICE 'No active loan with ID %', p_loan_id;
        RETURN;
    END IF;

    UPDATE book_loans
    SET status = 'RETURNED'
    WHERE loan_id = p_loan_id;

    UPDATE books
    SET available_copies = available_copies + v_quantity
    WHERE book_id = v_book_id;

    RAISE NOTICE 'Loan % returned; % copies restored', p_loan_id, v_quantity;
END;
$$;

CALL return_book(1);
CALL return_book(1);   -- second call: already RETURNED, must not restore copies again
-- Expected: first call restores copies and prints confirmation;
--           second call prints "No active loan with ID 1"

-- ---- Task 7: Explicit cursor for books with few copies ----
CREATE OR REPLACE PROCEDURE show_low_stock_books()
LANGUAGE plpgsql
AS $$
DECLARE
    v_book   record;
    c_low    CURSOR FOR
        SELECT title, available_copies
        FROM books
        WHERE available_copies <= 2
        ORDER BY book_id;
BEGIN
    OPEN c_low;
    LOOP
        FETCH c_low INTO v_book;
        EXIT WHEN NOT FOUND;
        RAISE NOTICE 'Low stock: % (% remaining)', v_book.title, v_book.available_copies;
    END LOOP;
    CLOSE c_low;
END;
$$;

CALL show_low_stock_books();
-- Expected: at least "Introduction to Algorithms (1 remaining)" is reported

-- ---- Task 8: Borrow zero copies and handle the exception ----
DO $$
BEGIN
    CALL borrow_book(3, 'STU104', 0);
EXCEPTION WHEN invalid_parameter_value THEN
    RAISE NOTICE 'Handled expected error: %', SQLERRM;
END;
$$ LANGUAGE plpgsql;
-- Expected: "Handled expected error: Quantity must be positive"

-- ---- Task 9: Final state of both tables ----
SELECT * FROM books ORDER BY book_id;
SELECT * FROM book_loans ORDER BY loan_id;
-- Expected: book 1 -> 4 copies (2 borrowed, then returned), book 2 -> 1 copy,
--           book 3 -> 5 copies (1 still out on loan to STU102)
-- Loans: loan 1 RETURNED, loan 2 (book 3, STU102) ACTIVE
