-- ============================================================
-- ICT371 PostgreSQL Scenario Assignment
-- Scenario 2: Computer Laboratory Reservations
-- Student: Stanslous Chipampe  |  Student Number: 202406233
-- ============================================================

-- ---- Task 1: Create tables and seed data ----
DROP TABLE IF EXISTS reservations CASCADE;
DROP TABLE IF EXISTS lab_sessions CASCADE;

CREATE TABLE lab_sessions (
    session_id              integer PRIMARY KEY,
    session_name             text NOT NULL,
    available_workstations   integer NOT NULL CHECK (available_workstations >= 0)
);

CREATE TABLE reservations (
    reservation_id   integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id       integer NOT NULL REFERENCES lab_sessions(session_id),
    lecturer_name    text NOT NULL,
    workstations     integer NOT NULL CHECK (workstations > 0),
    status           text NOT NULL CHECK (status IN ('ACTIVE', 'CANCELLED'))
);

INSERT INTO lab_sessions (session_id, session_name, available_workstations)
VALUES (1, 'ICT371 Databases Practical', 10),
       (2, 'ICT372 Networks Practical', 2),
       (3, 'ICT210 Programming Practical', 15);

SELECT * FROM lab_sessions ORDER BY session_id;
-- Expected: 3 rows (session 1: 10, session 2: 2, session 3: 15)

-- ---- Task 2: IF ELSIF ELSE on session capacity ----
DO $$
DECLARE
    v_workstations integer;
BEGIN
    SELECT available_workstations INTO v_workstations
    FROM lab_sessions WHERE session_id = 2;

    IF v_workstations = 0 THEN
        RAISE NOTICE 'Session full';
    ELSIF v_workstations <= 2 THEN
        RAISE NOTICE 'Session nearly full: % workstations left', v_workstations;
    ELSE
        RAISE NOTICE 'Session has enough workstations: % left', v_workstations;
    END IF;
END;
$$ LANGUAGE plpgsql;
-- Expected message: "Session nearly full: 2 workstations left"

-- ---- Task 3: WHILE loop (preparation reminders) and FOR loop (workstation checks) ----
DO $$
DECLARE
    v_reminder integer := 1;
BEGIN
    WHILE v_reminder <= 3 LOOP
        RAISE NOTICE 'Session preparation reminder #%', v_reminder;
        v_reminder := v_reminder + 1;
    END LOOP;

    FOR v_check IN 1..3 LOOP
        RAISE NOTICE 'Workstation check #%', v_check;
    END LOOP;
END;
$$ LANGUAGE plpgsql;
-- Expected: 3 preparation reminder notices, then 3 workstation-check notices

-- ---- Task 4: reserve_workstations procedure ----
CREATE OR REPLACE PROCEDURE reserve_workstations(
    p_session_id    integer,
    p_lecturer_name text,
    p_workstations  integer
)
LANGUAGE plpgsql
AS $$
DECLARE
    v_available       integer;
    v_reservation_id  integer;
BEGIN
    IF p_workstations <= 0 THEN
        RAISE EXCEPTION 'Workstation count must be positive'
            USING ERRCODE = '22023';
    END IF;

    SELECT available_workstations INTO v_available
    FROM lab_sessions
    WHERE session_id = p_session_id
    FOR UPDATE;

    IF NOT FOUND THEN
        RAISE NOTICE 'Session % does not exist', p_session_id;
        RETURN;
    ELSIF v_available < p_workstations THEN
        RAISE NOTICE 'Insufficient capacity: only % workstations available', v_available;
        RETURN;
    END IF;

    UPDATE lab_sessions
    SET available_workstations = available_workstations - p_workstations
    WHERE session_id = p_session_id;

    INSERT INTO reservations (session_id, lecturer_name, workstations, status)
    VALUES (p_session_id, p_lecturer_name, p_workstations, 'ACTIVE')
    RETURNING reservation_id INTO v_reservation_id;

    RAISE NOTICE 'Reservation % created for %', v_reservation_id, p_lecturer_name;
END;
$$;

-- ---- Task 5: Call reserve_workstations — two valid, one exceeding capacity ----
CALL reserve_workstations(1, 'Dr. Banda', 4);
CALL reserve_workstations(3, 'Mr. Phiri', 6);
CALL reserve_workstations(2, 'Mrs. Zulu', 5);   -- exceeds the 2 workstations available

SELECT * FROM lab_sessions ORDER BY session_id;
-- Expected: session 1 -> 6 left, session 2 -> 2 left (unchanged), session 3 -> 9 left

SELECT * FROM reservations ORDER BY reservation_id;
-- Expected: 2 ACTIVE reservations only (Mrs. Zulu's request was never recorded)

-- ---- Task 6: cancel_reservation procedure (idempotent on repeat call) ----
CREATE OR REPLACE PROCEDURE cancel_reservation(p_reservation_id integer)
LANGUAGE plpgsql
AS $$
DECLARE
    v_session_id   integer;
    v_workstations integer;
BEGIN
    SELECT session_id, workstations
    INTO v_session_id, v_workstations
    FROM reservations
    WHERE reservation_id = p_reservation_id AND status = 'ACTIVE'
    FOR UPDATE;

    IF NOT FOUND THEN
        RAISE NOTICE 'No active reservation with ID %', p_reservation_id;
        RETURN;
    END IF;

    UPDATE reservations
    SET status = 'CANCELLED'
    WHERE reservation_id = p_reservation_id;

    UPDATE lab_sessions
    SET available_workstations = available_workstations + v_workstations
    WHERE session_id = v_session_id;

    RAISE NOTICE 'Reservation % cancelled; % workstations released', p_reservation_id, v_workstations;
END;
$$;

CALL cancel_reservation(1);
CALL cancel_reservation(1);   -- second call: already CANCELLED, must not release again
-- Expected: first call releases workstations and prints confirmation;
--           second call prints "No active reservation with ID 1"

-- ---- Task 7: Explicit cursor for sessions with few workstations ----
CREATE OR REPLACE PROCEDURE show_low_availability_sessions()
LANGUAGE plpgsql
AS $$
DECLARE
    v_session  record;
    c_low      CURSOR FOR
        SELECT session_name, available_workstations
        FROM lab_sessions
        WHERE available_workstations <= 2
        ORDER BY session_id;
BEGIN
    OPEN c_low;
    LOOP
        FETCH c_low INTO v_session;
        EXIT WHEN NOT FOUND;
        RAISE NOTICE 'Low availability: % (% remaining)', v_session.session_name, v_session.available_workstations;
    END LOOP;
    CLOSE c_low;
END;
$$;

CALL show_low_availability_sessions();
-- Expected: at least "ICT372 Networks Practical (2 remaining)" is reported

-- ---- Task 8: Request zero workstations and handle the exception ----
DO $$
BEGIN
    CALL reserve_workstations(3, 'Ms. Tembo', 0);
EXCEPTION WHEN invalid_parameter_value THEN
    RAISE NOTICE 'Handled expected error: %', SQLERRM;
END;
$$ LANGUAGE plpgsql;
-- Expected: "Handled expected error: Workstation count must be positive"

-- ---- Task 9: Final state of both tables ----
SELECT * FROM lab_sessions ORDER BY session_id;
SELECT * FROM reservations ORDER BY reservation_id;
