-- ============================================================
-- ICT371 PostgreSQL Scenario Assignment
-- Scenario 3: Student Hostel Room Allocation
-- Student: Stanslous Chipampe  |  Student Number: 202406233
-- ============================================================

-- ---- Task 1: Create tables and seed data ----
DROP TABLE IF EXISTS allocations CASCADE;
DROP TABLE IF EXISTS hostel_rooms CASCADE;

CREATE TABLE hostel_rooms (
    room_id          integer PRIMARY KEY,
    room_name         text NOT NULL,
    available_spaces  integer NOT NULL CHECK (available_spaces >= 0)
);

CREATE TABLE allocations (
    allocation_id   integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    room_id         integer NOT NULL REFERENCES hostel_rooms(room_id),
    student_number  text NOT NULL,
    status          text NOT NULL CHECK (status IN ('ACTIVE', 'CHECKED_OUT'))
);

INSERT INTO hostel_rooms (room_id, room_name, available_spaces)
VALUES (1, 'Block A Room 101', 3),
       (2, 'Block A Room 102', 1),
       (3, 'Block B Room 205', 4);

SELECT * FROM hostel_rooms ORDER BY room_id;
-- Expected: 3 rows (room 1: 3 spaces, room 2: 1 space, room 3: 4 spaces)

-- ---- Task 2: IF ELSIF ELSE on room occupancy ----
DO $$
DECLARE
    v_spaces integer;
BEGIN
    SELECT available_spaces INTO v_spaces
    FROM hostel_rooms WHERE room_id = 2;

    IF v_spaces = 0 THEN
        RAISE NOTICE 'Room full';
    ELSIF v_spaces = 1 THEN
        RAISE NOTICE 'Room has one space left';
    ELSE
        RAISE NOTICE 'Room has several spaces: % remaining', v_spaces;
    END IF;
END;
$$ LANGUAGE plpgsql;
-- Expected message: "Room has one space left"

-- ---- Task 3: WHILE loop (inspection days) and FOR loop (room checks) ----
DO $$
DECLARE
    v_day integer := 1;
BEGIN
    WHILE v_day <= 3 LOOP
        RAISE NOTICE 'Hostel inspection day %', v_day;
        v_day := v_day + 1;
    END LOOP;

    FOR v_check IN 1..3 LOOP
        RAISE NOTICE 'Room check #%', v_check;
    END LOOP;
END;
$$ LANGUAGE plpgsql;
-- Expected: 3 inspection-day notices, then 3 room-check notices

-- ---- Task 4: allocate_room procedure ----
-- Note: a hostel allocation is one bed space per student, so there is no
-- quantity parameter here (unlike the other scenarios) — only a room and a
-- student number. Availability is reduced by exactly one each call.
CREATE OR REPLACE PROCEDURE allocate_room(
    p_room_id        integer,
    p_student_number text
)
LANGUAGE plpgsql
AS $$
DECLARE
    v_available     integer;
    v_allocation_id integer;
BEGIN
    IF p_student_number IS NULL OR btrim(p_student_number) = '' THEN
        RAISE EXCEPTION 'Student number must not be blank'
            USING ERRCODE = '22023';
    END IF;

    SELECT available_spaces INTO v_available
    FROM hostel_rooms
    WHERE room_id = p_room_id
    FOR UPDATE;

    IF NOT FOUND THEN
        RAISE NOTICE 'Room % does not exist', p_room_id;
        RETURN;
    ELSIF v_available < 1 THEN
        RAISE NOTICE 'Room % is full: no spaces available', p_room_id;
        RETURN;
    END IF;

    UPDATE hostel_rooms
    SET available_spaces = available_spaces - 1
    WHERE room_id = p_room_id;

    INSERT INTO allocations (room_id, student_number, status)
    VALUES (p_room_id, p_student_number, 'ACTIVE')
    RETURNING allocation_id INTO v_allocation_id;

    RAISE NOTICE 'Allocation % created for student %', v_allocation_id, p_student_number;
END;
$$;

-- ---- Task 5: Call allocate_room — two valid, one to a full room ----
CALL allocate_room(1, 'STU201');
CALL allocate_room(3, 'STU202');
CALL allocate_room(2, 'STU203');   -- room 2 only has 1 space
CALL allocate_room(2, 'STU204');   -- this one should find room 2 full

SELECT * FROM hostel_rooms ORDER BY room_id;
-- Expected: room 1 -> 2 spaces, room 2 -> 0 spaces, room 3 -> 3 spaces

SELECT * FROM allocations ORDER BY allocation_id;
-- Expected: 3 ACTIVE allocations (STU204's request was never recorded)

-- ---- Task 6: check_out procedure (idempotent on repeat call) ----
CREATE OR REPLACE PROCEDURE check_out(p_allocation_id integer)
LANGUAGE plpgsql
AS $$
DECLARE
    v_room_id integer;
BEGIN
    SELECT room_id
    INTO v_room_id
    FROM allocations
    WHERE allocation_id = p_allocation_id AND status = 'ACTIVE'
    FOR UPDATE;

    IF NOT FOUND THEN
        RAISE NOTICE 'No active allocation with ID %', p_allocation_id;
        RETURN;
    END IF;

    UPDATE allocations
    SET status = 'CHECKED_OUT'
    WHERE allocation_id = p_allocation_id;

    UPDATE hostel_rooms
    SET available_spaces = available_spaces + 1
    WHERE room_id = v_room_id;

    RAISE NOTICE 'Allocation % checked out; 1 space released in room %', p_allocation_id, v_room_id;
END;
$$;

CALL check_out(1);
CALL check_out(1);   -- second call: already CHECKED_OUT, must not free another space
-- Expected: first call releases a space and prints confirmation;
--           second call prints "No active allocation with ID 1"

-- ---- Task 7: Explicit cursor for full or nearly full rooms ----
CREATE OR REPLACE PROCEDURE show_full_or_near_full_rooms()
LANGUAGE plpgsql
AS $$
DECLARE
    v_room  record;
    c_full  CURSOR FOR
        SELECT room_name, available_spaces
        FROM hostel_rooms
        WHERE available_spaces <= 1
        ORDER BY room_id;
BEGIN
    OPEN c_full;
    LOOP
        FETCH c_full INTO v_room;
        EXIT WHEN NOT FOUND;
        RAISE NOTICE 'Full or nearly full: % (% remaining)', v_room.room_name, v_room.available_spaces;
    END LOOP;
    CLOSE c_full;
END;
$$;

CALL show_full_or_near_full_rooms();
-- Expected: at least "Block A Room 102 (0 remaining)" is reported

-- ---- Task 8: Attempt allocation with a blank student number ----
DO $$
BEGIN
    CALL allocate_room(3, '');
EXCEPTION WHEN invalid_parameter_value THEN
    RAISE NOTICE 'Handled expected error: %', SQLERRM;
END;
$$ LANGUAGE plpgsql;
-- Expected: "Handled expected error: Student number must not be blank"

-- ---- Task 9: Final state of both tables ----
SELECT * FROM hostel_rooms ORDER BY room_id;
SELECT * FROM allocations ORDER BY allocation_id;
