-- ============================================================
-- ICT371 PostgreSQL Scenario Assignment
-- Scenario 4: Campus Clinic Medicine Dispensing
-- Student: Stanslous Chipampe  |  Student Number: 202406233
-- ============================================================

-- ---- Task 1: Create tables and seed data ----
DROP TABLE IF EXISTS dispensing_records CASCADE;
DROP TABLE IF EXISTS medicines CASCADE;

CREATE TABLE medicines (
    medicine_id      integer PRIMARY KEY,
    medicine_name     text NOT NULL,
    stock_quantity     integer NOT NULL CHECK (stock_quantity >= 0)
);

CREATE TABLE dispensing_records (
    record_id        integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    medicine_id       integer NOT NULL REFERENCES medicines(medicine_id),
    student_number    text NOT NULL,
    quantity          integer NOT NULL CHECK (quantity > 0),
    status            text NOT NULL CHECK (status IN ('DISPENSED', 'REVERSED'))
);

INSERT INTO medicines (medicine_id, medicine_name, stock_quantity)
VALUES (1, 'Paracetamol 500mg', 50),
       (2, 'ORS Sachets', 2),
       (3, 'Amoxicillin 250mg', 30);

SELECT * FROM medicines ORDER BY medicine_id;
-- Expected: 3 rows (medicine 1: 50, medicine 2: 2, medicine 3: 30)

-- ---- Task 2: IF ELSIF ELSE on stock level ----
DO $$
DECLARE
    v_stock integer;
BEGIN
    SELECT stock_quantity INTO v_stock
    FROM medicines WHERE medicine_id = 2;

    IF v_stock = 0 THEN
        RAISE NOTICE 'Medicine out of stock';
    ELSIF v_stock <= 2 THEN
        RAISE NOTICE 'Medicine low on stock: % remaining', v_stock;
    ELSE
        RAISE NOTICE 'Medicine sufficiently stocked: % remaining', v_stock;
    END IF;
END;
$$ LANGUAGE plpgsql;
-- Expected message: "Medicine low on stock: 2 remaining"

-- ---- Task 3: WHILE loop (stock review days) and FOR loop (shelf inspections) ----
DO $$
DECLARE
    v_day integer := 1;
BEGIN
    WHILE v_day <= 3 LOOP
        RAISE NOTICE 'Stock review day %', v_day;
        v_day := v_day + 1;
    END LOOP;

    FOR v_shelf IN 1..3 LOOP
        RAISE NOTICE 'Shelf inspection #%', v_shelf;
    END LOOP;
END;
$$ LANGUAGE plpgsql;
-- Expected: 3 stock-review-day notices, then 3 shelf-inspection notices

-- ---- Task 4: dispense_medicine procedure ----
CREATE OR REPLACE PROCEDURE dispense_medicine(
    p_medicine_id    integer,
    p_student_number text,
    p_quantity       integer
)
LANGUAGE plpgsql
AS $$
DECLARE
    v_stock    integer;
    v_record_id integer;
BEGIN
    IF p_quantity <= 0 THEN
        RAISE EXCEPTION 'Quantity must be positive'
            USING ERRCODE = '22023';
    END IF;

    SELECT stock_quantity INTO v_stock
    FROM medicines
    WHERE medicine_id = p_medicine_id
    FOR UPDATE;

    IF NOT FOUND THEN
        RAISE NOTICE 'Medicine % does not exist', p_medicine_id;
        RETURN;
    ELSIF v_stock < p_quantity THEN
        RAISE NOTICE 'Insufficient stock: only % available', v_stock;
        RETURN;
    END IF;

    UPDATE medicines
    SET stock_quantity = stock_quantity - p_quantity
    WHERE medicine_id = p_medicine_id;

    INSERT INTO dispensing_records (medicine_id, student_number, quantity, status)
    VALUES (p_medicine_id, p_student_number, p_quantity, 'DISPENSED')
    RETURNING record_id INTO v_record_id;

    RAISE NOTICE 'Dispensing record % created for student %', v_record_id, p_student_number;
END;
$$;

-- ---- Task 5: Call dispense_medicine — two valid, one exceeding stock ----
CALL dispense_medicine(1, 'STU301', 10);
CALL dispense_medicine(3, 'STU302', 5);
CALL dispense_medicine(2, 'STU303', 8);   -- exceeds the 2 units available

SELECT * FROM medicines ORDER BY medicine_id;
-- Expected: medicine 1 -> 40, medicine 2 -> 2 (unchanged), medicine 3 -> 25

SELECT * FROM dispensing_records ORDER BY record_id;
-- Expected: 2 DISPENSED records only (STU303's request was never recorded)

-- ---- Task 6: reverse_dispensing procedure (idempotent on repeat call) ----
CREATE OR REPLACE PROCEDURE reverse_dispensing(p_record_id integer)
LANGUAGE plpgsql
AS $$
DECLARE
    v_medicine_id integer;
    v_quantity    integer;
BEGIN
    SELECT medicine_id, quantity
    INTO v_medicine_id, v_quantity
    FROM dispensing_records
    WHERE record_id = p_record_id AND status = 'DISPENSED'
    FOR UPDATE;

    IF NOT FOUND THEN
        RAISE NOTICE 'No dispensed record with ID % to reverse', p_record_id;
        RETURN;
    END IF;

    UPDATE dispensing_records
    SET status = 'REVERSED'
    WHERE record_id = p_record_id;

    UPDATE medicines
    SET stock_quantity = stock_quantity + v_quantity
    WHERE medicine_id = v_medicine_id;

    RAISE NOTICE 'Record % reversed; % units restored to stock', p_record_id, v_quantity;
END;
$$;

CALL reverse_dispensing(1);
CALL reverse_dispensing(1);   -- second call: already REVERSED, stock must not be restored again
-- Expected: first call restores stock and prints confirmation;
--           second call prints "No dispensed record with ID 1 to reverse"

-- ---- Task 7: Explicit cursor for medicines below the low-stock threshold ----
CREATE OR REPLACE PROCEDURE show_low_stock_medicines()
LANGUAGE plpgsql
AS $$
DECLARE
    v_medicine  record;
    c_low       CURSOR FOR
        SELECT medicine_name, stock_quantity
        FROM medicines
        WHERE stock_quantity <= 5
        ORDER BY medicine_id;
BEGIN
    OPEN c_low;
    LOOP
        FETCH c_low INTO v_medicine;
        EXIT WHEN NOT FOUND;
        RAISE NOTICE 'Low stock: % (% remaining)', v_medicine.medicine_name, v_medicine.stock_quantity;
    END LOOP;
    CLOSE c_low;
END;
$$;

CALL show_low_stock_medicines();
-- Expected: at least "ORS Sachets (2 remaining)" is reported

-- ---- Task 8: Request a negative dispensing quantity and handle the exception ----
DO $$
BEGIN
    CALL dispense_medicine(3, 'STU304', -5);
EXCEPTION WHEN invalid_parameter_value THEN
    RAISE NOTICE 'Handled expected error: %', SQLERRM;
END;
$$ LANGUAGE plpgsql;
-- Expected: "Handled expected error: Quantity must be positive"

-- ---- Task 9: Final state of both tables ----
SELECT * FROM medicines ORDER BY medicine_id;
SELECT * FROM dispensing_records ORDER BY record_id;
